## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - 0.6.1
  - 0.6.2
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# dependencies that are not in METADATA
#before_script:
#  - julia -e 'Pkg.clone("git://github.com/acroy/Expokit.jl.git")'

## allow failures (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: 0.6.1
    - julia: 0.6.2
    - julia: nightly

## uncomment and modify the following lines to manually install system packages
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("LazySets"); Pkg.test("LazySets"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter"); Pkg.add("GR")'
  - julia -e 'cd(Pkg.dir("LazySets")); include(joinpath("docs", "make.jl"))'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("LazySets")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("LazySets")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
