## Documentation: http://docs.travis-ci.com/user/languages/julia/
codecov: true

language: julia

os:
  - linux

julia:
  - 1.0
  - 1.4

cache:
  directories:
  - $HOME/.julia/artifacts

notifications:
  email: false

git:
  depth: 99999999

branches:
  only:
  - master
  - gh-pages  # documentation
  - /^testing-.*$/  # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/  # version tags

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate();
                                               Pkg.add(PackageSpec(name="ModelingToolkit", version="3.10.2"))'
        - travis_wait 30 julia --project=docs/ docs/make.jl
      after_success: skip
