## Documentation: http://docs.travis-ci.com/user/languages/julia/
codecov: true

language: julia

os:
  - linux

julia:
  - 1.2
  - 1.5

cache:
  directories:
  - $HOME/.julia/artifacts

notifications:
  email: false

git:
  depth: 99999999

branches:
  only:
  - master
  - gh-pages  # documentation
  - /^testing-.*$/  # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/  # version tags

script:
 - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.build(verbose=true); Pkg.test(coverage=true); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate();'
        - travis_wait 40 julia --project=docs/ docs/make.jl
      after_success: skip
