[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Expokit = "a1e7a1ef-7a5d-5822-a38c-be74e1bb89f4"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TaylorModels = "314ce334-5f6e-57ae-acf6-00b6e903104a"

[compat]
BenchmarkTools = "≥ 0.4.2"
Documenter = "^0.23"
StaticArrays = "≥ 0.10.3"
